name: CI

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        go-version: ["stable"]
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install Goose
      run: |
        go install github.com/goose-lang/goose/cmd/goose@latest
    - name: Install dependencies
      run: |
        go get -t ./...
    - name: Check style
      run: |
        gofmt -w .
        git diff --exit-code
        go vet ./...
    - name: Test
      run: |
        go test -v ./...
        make goose-output
